 1. Create a 5X2 integer array from a range between 100 to
200 such that the difference between each element is 10.

In [1]:
import numpy as np

In [3]:
print(" Creating 5X2 array using numpy.arange :")
Numpy_Array = np.arange(100, 200, 10)
Array = Numpy_Array.reshape(5,2)
print (Array)

 Creating 5X2 array using numpy.arange :
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


2. Write a NumPy program to create a 3x3x3 array filled
with arbitrary values and find the minimum and maximum
values.

In [14]:
array = np.random.random((3, 3, 3))
print('The Matrix is ',array)
print('The minimum value is: ',np.min(array),'The Maximum value is:',np.max(array),sep='\n')

The Matrix is  [[[0.63196319 0.29867489 0.37672148]
  [0.76343659 0.90935696 0.20572153]
  [0.73214664 0.5334567  0.7876562 ]]

 [[0.37891451 0.53806561 0.29724818]
  [0.50036723 0.49508641 0.99508615]
  [0.24406656 0.65113033 0.92508451]]

 [[0.43751415 0.96856124 0.62797343]
  [0.21430192 0.32392507 0.63606622]
  [0.71463734 0.12021505 0.16764499]]]
The minimum value is: 
0.12021504699105179
The Maximum value is:
0.9950861538263261


3. Write a NumPy program to create a 5x5 zero matrix
with elements on the main diagonal equal to 1, 2, 3, 4,
5.

In [15]:
zero_array= np.zeros((5,5))
print(zero_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


4. Given an array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9 i)
Extract all odd numbers from arr
ii) Replace all odd numbers in arr with -1

In [31]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ])
print('The array is :',arr)
print("Odd number are:")
for i in arr: 
    if(i%2==1): 
        print(i)
arr[(arr%2 == 1)]=-1
print('The final array is:',arr)

The array is : [0 1 2 3 4 5 6 7 8 9]
Odd number are:
1
3
5
7
9
The final array is: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


5.Write a NumPy program to create a 3x3 identity matrix,
i.e. diagonal elements are 1,the rest are 0.

In [32]:
x = np.diag([1, 1, 1])
print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


6. Write a NumPy program to convert an array to a float
type.

In [37]:
arr_fl = np.array([[1,2], [3,4], [5,6]] , dtype = np.float64)
print(" A Float Array: \n" , arr_fl)
print(type(arr_fl))

 A Float Array: 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
<class 'numpy.ndarray'>


7. Write a NumPy program to generate five random
numbers from the normal distribution.

In [38]:
x = np.random.normal(size=5)
print(x)

[ 1.26801067 -1.70247485 -0.80906967  2.42187745  0.97999357]


8. Following is the input NumPy array delete column two
and insert following new column in its place.
sampleArray=numpy.array([[34,43,73],[82,22,12],[53,94
, 66]]) newColumn = numpy.array([[10,10,10]])

In [48]:
print("Printing Original array")
sampleArray=np.array([[34,43,73],[82,22,12],[53,94 , 66]])
print(sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print(sampleArray)

arr = np.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


9. Write a NumPy program to compute the multiplication
of two given matrices.

In [54]:
p= np.array(([1,2],[3,4]))
q= np.array(([5,6],[7,8]))
result=np.dot(p,q)
print(result)

[[19 22]
 [43 50]]


10. Write a NumPy program to create a random vector of
size 10 and sort it.

In [55]:
x = np.random.random(10)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.56685652 0.06690938 0.99121957 0.89088564 0.73789184 0.42843598
 0.97188893 0.76881076 0.8521632  0.0075324 ]
Sorted array:
[0.0075324  0.06690938 0.42843598 0.56685652 0.73789184 0.76881076
 0.8521632  0.89088564 0.97188893 0.99121957]


11. Write a NumPy program to compute the covariance
matrix of two arrays.

In [56]:
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("Original array1:")
print(x)
print("Original array1:")
print(y)
print("Covariance matrix of the said arrays:",np.cov(x, y))

Original array1:
[0 1 2]
Original array1:
[2 1 0]
Covariance matrix of the said arrays: [[ 1. -1.]
 [-1.  1.]]


12.Create a 4X2 integer array and Prints its
: i)The shape of an array.
ii) Array dimensions.
iii) The Length of each element of the array in bytes

In [60]:
firstArray = np.empty([4,2], dtype = np.uint16) 
print("Printing Array")
print(firstArray)

print("Printing numpy array Attributes")
print("i). Array Shape is: ", firstArray.shape)
print("ii). Array dimensions are ", firstArray.ndim)
print("iii). Length of each element of array in bytes is ", firstArray.itemsize)

Printing Array
[[    0     0]
 [    0 16392]
 [    0     0]
 [    0 16392]]
Printing numpy array Attributes
i). Array Shape is:  (4, 2)
ii). Array dimensions are  2
iii). Length of each element of array in bytes is  2


In [ ]:
13. Write a NumPy program to concatenate element-wise
two arrays of string.

In [62]:
x1 = np.array([[1,1,1],[1,1,1],[1,1,1]])
x2 = np.array([[1,1,1],[1,1,1],[1,1,1]])
print("Array1:")
print(x1)
print("Array2:")
print(x2)
new_array = np.add(x1, x2)
print("new array:")
print(new_array)

Array1:
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Array2:
[[1 1 1]
 [1 1 1]
 [1 1 1]]
new array:
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [64]:
print(np.add(x1,x1))

[[2 2 2]
 [2 2 2]
 [2 2 2]]


14. Write a NumPy program to capitalize the first letter,
lowercase, uppercase, swapcase, title-case of all the
elements of a given array.

In [66]:
x = np.array(['nihar','ranjan','swain'], dtype=np.str)
print("Original Array:")
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)

Original Array:
['nihar' 'ranjan' 'swain']

Capitalized:  ['Nihar' 'Ranjan' 'Swain']
Lowered:  ['nihar' 'ranjan' 'swain']
Uppered:  ['NIHAR' 'RANJAN' 'SWAIN']
Swapcased:  ['NIHAR' 'RANJAN' 'SWAIN']
Titlecased:  ['Nihar' 'Ranjan' 'Swain']


15. Write a NumPy program to convert a given array into
a list.

In [67]:
print("Array:")
arr = np.array([1, 2, 4, 5,6,7,8,9,20])  
print(arr)
print(type(arr))
  

lis = arr.tolist()
  
print("List:")
print(lis)
print(type(lis))

Array:
[ 1  2  4  5  6  7  8  9 20]
<class 'numpy.ndarray'>
List:
[1, 2, 4, 5, 6, 7, 8, 9, 20]
<class 'list'>


16. Write a NumPy program to compute the sum of all
elements, sum of each column and sum of each row of a
given array.

In [72]:
x = np.array(([0,1],[2,3],[4,5],[6,7],[8,9]))
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Sum of all elements:
45
Sum of each column:
[20 25]
Sum of each row:
[ 1  5  9 13 17]


17. Write a NumPy program to create a random 10x4
array and extract the first five rows of the array and store
them into a variable.

In [73]:
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
print(y)

Original array: 
[[0.20285783 0.4393715  0.35179073 0.05091552]
 [0.4168404  0.03684295 0.04611252 0.42442766]
 [0.53723033 0.17655349 0.79029307 0.64361057]
 [0.19074729 0.65580811 0.50023947 0.77430746]
 [0.84039129 0.9759608  0.82355079 0.16708599]
 [0.60789923 0.35086961 0.08876777 0.25654958]
 [0.13310395 0.73596379 0.73545142 0.77440593]
 [0.87621204 0.30925856 0.26778836 0.92480597]
 [0.75109648 0.11176462 0.09509894 0.83729713]
 [0.94592709 0.97452102 0.74947432 0.3374349 ]]
First 5 rows of the above array:
[[0.20285783 0.4393715  0.35179073 0.05091552]
 [0.4168404  0.03684295 0.04611252 0.42442766]
 [0.53723033 0.17655349 0.79029307 0.64361057]
 [0.19074729 0.65580811 0.50023947 0.77430746]
 [0.84039129 0.9759608  0.82355079 0.16708599]]


18. Write a NumPy program to get the unique elements ofa 1D and 2D array.

In [74]:
_1D = np.random.randint(10, size=6)
_2D = np.random.randint(10, size=(3, 4)) 
rslt_1d = np.unique(_1D)
rslt_2d = np.unique(_2D)
print(rslt_1d,rslt_2d,sep='\n')

[5 6 7 9]
[1 2 3 4 5 6 7 8]


In [77]:
_1D = np.array([1,2,3,4,4,4,3,2])
_2D = np.array([[1,2,3],[4,3,2],[1,2,5]])
rslt_1d = np.unique(_1D)
rslt_2d = np.unique(_2D)
print(rslt_1d,rslt_2d,sep='\n')

[1 2 3 4]
[1 2 3 4 5]


19. Write a NumPy program to get the unique elements of
an array.
arr= [ -10 12.12 -0.2]

In [80]:
arr=np.array([-10, 12.12, -0.2])
print("The Array is:",arr)
print("Unique elements are:",np.unique(arr))

The Array is: [-10.    12.12  -0.2 ]
Unique elements are: [-10.    -0.2   12.12]


20. Write a NumPy program to save a given array to a text
file and load it. You have to save and load files using
numpy library .

In [86]:
List = [1, 2, 3, 4, 5]
Array = np.array(List)
print('Array:', Array)

file = open("text1.txt", "w+")
 
content = str(Array)
file.write(content)
file.close()
 
file = open("text1.txt", "r")
content = file.read()
 
print("Content in text1.txt:", content)
file.close()

Array: [1 2 3 4 5]
Content in text1.txt: [1 2 3 4 5]
